services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - CALLIDOS_APP_JWT_SECRET=${CALLIDOS_APP_JWT_SECRET}
      - CALLIDOS_APP_JWT_EXPIRATION_MS=${CALLIDOS_APP_JWT_EXPIRATION_MS}

  db:
    image: mysql:5.7
    environment:
      - DB_MYSQL_DATABASE=${MYSQL_DATABASE}
      - DB_MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
